### ISSUE TITLE
Mismatching between the checkpoints and the config file

### ISSUE THREAD

**Issue by yzhouas** [hasanirtiza/PedesFormer#4] opened 2022-03-01 09:23 UTC
Hi, thanks for the good work.
I download the checkpoints from the google drive link, and use the config file you mentioned. However, when I use the image_demo.py for testing, there are some mismatching problems while loading the weights. Do you happen to know the reasons and the ways to resolve it? Thanks!
![image](https://user-images.githubusercontent.com/19570164/156141572-2d3258a7-91ea-4e2f-bba0-68faa7d5c533.png)

**Comment by hasanirtiza** [comment] 2022-03-01 09:44
Can you confirm that the output is fine when you run the demo ? I mean does your demo image get some detections after running the script ?

**Comment by yzhouas** [comment] 2022-03-01 09:51
It seems the backbone in the checkpoint is form HRNet because I saw many keywords from HRNet (I guess maybe you upload the wrong checkpoints?) . Yes, the detections will be messed up.

**Comment by hasanirtiza** [comment] 2022-03-01 09:58
`Yes, the detections will be messed up.` Will be or is it messed up ?

Paste the whole error log along with the command you use to run the demo.

**Comment by yzhouas** [comment] 2022-03-01 10:12
Thanks. The detection results are messed up because the weights are not loaded.  The error logs are two folds:
(1) Unexpected keys like backbone.bn1 (it seems from HRNet backbone) as in the first screen shot, and 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/19570164/156149851-b609303f-1da1-492e-92f7-b7a8868f9fec.png">
(2) Missing keys are the keys in the Swin-transformer like patch_embed.
I run the code by using:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/19570164/156149979-01f0916e-b2fa-4912-9588-8a4a68ddca68.png">

The checkpoints.pth is renamed from the downloaded one in Google drive. 

Thanks!

**Comment by yzhouas** [comment] 2022-03-02 17:32
Sorry for bothering you. Could you share the new weights with me? Thanks so much!

**Comment by hasanirtiza** [comment] 2022-03-02 17:41
The issue is, I currently do not have access (I am away from the server) to the model. As I am away from office and cannot access it remotely. There is definitely a mess up between the original model and the uploaded one. It will take some time.

**Comment by yzhouas** [comment] 2022-03-02 17:46
Thanks for the explanation. Looking forward to the correct model weights!

**Comment by hasanirtiza** [comment] 2022-03-02 17:47
Hopefully will do it soon.

**Comment by hasanirtiza** [comment] 2022-05-29 08:05
@yzhouas Apologies for late response, it took so long because of the access issues I had to face. I have updated the links and also provided the config file, it should work now, incase you require.

**Comment by ljpadam** [comment] 2022-06-02 10:43
Thank you @hasanirtiza . The new model weight and config file work now.

**Comment by hasanirtiza** [comment] 2022-06-02 11:50
Great, I will close the issue then.

**Closed as completed** 2022-06-02 12:19 UTC
